spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/biblioswipe?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=#Proyecto2526
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Añade esto al final de tu archivo application.properties
#server.address=0.0.0.0
#Permitir tildes
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
server.address=0.0.0.0
# Aumentar el tamaño máximo permitido para archivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB